name: Config Name

# Short bio or description (displayed in the header)
description: Software Engineer && Data Scientist

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /resources/images/TannerPic.jpg
